version: '3.8'
services:
  video-processor-service:
    build: .
    container_name: video-processor-clean
    environment:
      AWS_S3_BUCKET_NAME: video-processing-bucket
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_ENDPOINT_URL: http://localstack-main:4566
      AWS_ATUALIZARSTATUS_SERVICE: http://solicitacao-service-clean:8080/api/solicitacoes/%d/arquivos/%d/status?status=%s
    command: [ "ffmpeg", "-version" ]
    ports:
      - "8081:8081"
    restart: no
    networks:
      - localstack-network
networks:
  localstack-network:
    external: true  # Usa a rede jรก criada
    driver: bridge