apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
        - name: localstack
          image: localstack/localstack
          ports:
            - containerPort: 4566
          env:
            - name: SERVICES
              value: "s3,sqs,lambda"
            - name: DEFAULT_REGION
              value: "us-east-1"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"